constants;

PSI = zeros(NSTATN, NSTREAM);
RHS = zeros(NSTATN, NSTREAM);
CZ = zeros(NSTATN, NSTREAM);
CR = zeros(NSTATN, NSTREAM);
RADIUS = zeros(NSTATN, NSTREAM);
HTOTAL = zeros(NSTATN, NSTREAM);
RCU = zeros(NSTATN, NSTREAM);
PTOTAL = zeros(NSTATN, NSTREAM);
DENSITY = zeros(NSTATN, NSTREAM);
ENTROPY = zeros(NSTATN, NSTREAM);
BETA = zeros(NSTATN, NSTREAM);