%% TRACING THERMODYNAMIC VARIABLES STATION-BY-STATION
function STREAM(PSI,CZ,CR,RCU,DENSITY,RADIUS,HTOTAL,KOUNT,TOTAL,RHS,NSTRM,NSTATN,ERRRHS,ERRDENS,OMEGLOS,ENTROPY)
constants;

%% UPDATING THE DENSITY ON THE INLET

for j=1:NSTRM
    CSQ = (RCU(1,J)/RADIUS(1,J))^2 + CZ(1,J)^2 + CR(1,J)^2;
    HSTATIC = HTOTAL(1,J) - CSQ/2;
    PSTATIC = PTOTAL(1,J)*(HSTATIC/HTOTAL(1,J))^GAMAM;
    DENSITY(1,J) = PSTATIC/(RGAS*HSTATIC/CP);
end

%%